name: Test pull request

on: [pull_request, workflow_dispatch]

jobs:
  test:
    runs-on: ubuntu-latest

    env:
      SUPABASE_ACCESS_TOKEN: ${{ secrets.SUPABASE_ACCESS_TOKEN }}
      SUPABASE_DB_PASSWORD: ${{ secrets.SUPABASE_PRODUCTION_DB_PASSWORD }}
      SUPABASE_PROJECT_ID: ${{ secrets.SUPABASE_PRODUCTION_PROJECT_ID }}

    defaults:
      run:
        working-directory: ./game

    steps:
      - uses: actions/checkout@v3
      - name: Login to Docker Hub
        uses: docker/login-action@v3
        with:
          username: ${{ secrets.DOCKERHUB_USERNAME }}
          password: ${{ secrets.DOCKERHUB_TOKEN }}
      - uses: pnpm/action-setup@v4
        with:
          version: 8.14.3
          run_install: true
      - run: pnpm supabase link --project-ref $SUPABASE_PROJECT_ID
      - run: pnpm supabase db start
      - run: pnpm gen:types
      - run: pnpm test
